In [5]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
print(inputs)

[0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]


In [6]:
def reLU_activation(inputs):
    output = []
    for i in inputs:
        output.append(max(0,i))
    return output
        

In [7]:
outputs = reLU_activation(inputs)
print(outputs)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [9]:
# using numpy to make it even smaller

import numpy as np
def reLU_activation_numpy(inputs):
    outputs = np.maximum(0, inputs)
    return outputs

outputs = reLU_activation_numpy(inputs)
print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [11]:
# Dense Layer with the activation function
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        #Initialize weights and biases
        #np.random.randn is a gaussian distribution which will provide values between -1 and 1 and 0.01 is multiplied to make the values smaller 
        # and close to each other thus fitting of data will be easier during training
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #To avoid transposing every time (inputs, neurons) is used rather than (neurons, inputs) 
        self.biases = np.zeros((1, n_neurons)) #default bias initialization
        pass
        
    def forward(self, inputs):
        #Calculate output values from inputs,weights and biases
        print("Weights are = ",self.weights)
        print("Biases are = ",self.biases)
        self.output = np.dot(inputs, self.weights) + self.biases
        pass
class Activation_ReLU:
    def activate(self, inputs):
        self.output = np.maximum(0,inputs)

In [12]:
#Create dataset
X, y = spiral_data(samples=100, classes=3)

#creating a dense layer with 2 input feature(size of each input = 2) and 3 output values(3 neurons)
neurons_layer1 = 3
dense_layer1 = Layer_Dense(len(X[0]), neurons_layer1)

dense_layer1.forward(X[:5]) #Takes only 5 rows of data or input-batch of 5 data rows 

print(dense_layer1.output) #For every input batch what is the value from each neuron(3 neurons (columns))

activation1 = Activation_ReLU() #Activation function

activation1.activate(dense_layer1.output) #Activates the neurons using ReLU

print(activation1.output) # output from the activation function

Weights are =  [[-0.01306527  0.01658131 -0.00118164]
 [-0.00680178  0.00666383 -0.0046072 ]]
Biases are =  [[0. 0. 0.]]
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]
