In [ ]:
#Dense Layer N/W or Fully Connected N/W

In [14]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        #Initialize weights and biases
        #np.random.randn is a gaussian distribution which will provide values between -1 and 1 and 0.01 is multiplied to make the values smaller 
        # and close to each other thus fitting of data will be easier during training
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #To avoid transposing every time (inputs, neurons) is used rather than (neurons, inputs) 
        self.biases = np.zeros((1, n_neurons)) #default bias initialization
        pass
        
    def forward(self, inputs):
        #Calculate output values from inputs,weights and biases
        print("Weights are = ",self.weights)
        print("Biases are = ",self.biases)
        self.output = np.dot(inputs, self.weights) + self.biases
        pass

In [19]:
#Create dataset
X, y = spiral_data(samples=100, classes=3)

#creating a dense layer with 2 input feature(size of each input = 2) and 3 output values(3 neurons)
neurons_layer1 = 3
dense_layer1 = Layer_Dense(len(X[0]), neurons_layer1)

dense_layer1.forward(X[:5]) #Takes only 5 rows of data or input-batch of 5 data rows 

print(dense_layer1.output) #For every input batch what is the value from each neuron(3 neurons (columns))


Weights are =  [[ 0.0002751   0.02232016 -0.0010498 ]
 [ 0.01367415 -0.01655344  0.00153644]]
Biases are =  [[0. 0. 0.]]
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.2344425e-04 -4.2612613e-05  8.7741073e-06]
 [ 2.5981691e-04 -1.5019374e-04  2.1353657e-05]
 [ 4.0532288e-04 -3.3390927e-04  3.8064085e-05]
 [ 5.5259373e-04 -6.4534455e-04  6.0963972e-05]]
