In [ ]:
# This dense layer will have each neurons which has a output and has a activation function and has softmax activation

In [8]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        #Initialize weights and biases
        #np.random.randn is a gaussian distribution which will provide values between -1 and 1 and 0.01 is multiplied to make the values smaller 
        # and close to each other thus fitting of data will be easier during training
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #To avoid transposing every time (inputs, neurons) is used rather than (neurons, inputs) 
        self.biases = np.zeros((1, n_neurons)) #default bias initialization
        pass
        
    def forward(self, inputs):
        #Calculate output values from inputs,weights and biases
        print("Weights are = ",self.weights)
        print("Biases are = ",self.biases)
        self.output = np.dot(inputs, self.weights) + self.biases
        pass
        
class Activation_ReLU:
    def activate(self, inputs):
        self.output = np.maximum(0,inputs)

class Activation_Softmax:
    #Forward pass
    def activate(self, inputs):
        #Get unnormalized input batch (inputs - max(input)). It is done so that the values if they are bigger like in the order of 1000 then e^1000
        # calculation may fail as it can overflow. So keeping the inputs in a small -ve range will give a +ve output with values between 0 and 1
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

        #Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

        self.output = probabilities

In [9]:
#Create dataset
X, y = spiral_data(samples=100, classes=3)

#creating a dense layer with 2 input feature(size of each input = 2) and 3 output values(3 neurons)
neurons_layer1 = 3
dense_layer1 = Layer_Dense(len(X[0]), neurons_layer1)

dense_layer1.forward(X[:5]) #Takes only 5 rows of data or input-batch of 5 data rows 

print("Dense Layer 1 output:: ")
print(dense_layer1.output) #For every input batch what is the value from each neuron(3 neurons (columns))

activation1 = Activation_ReLU() #Activation function 

activation1.activate(dense_layer1.output) #Activates the neurons using ReLU and it's not normalized

print("Dense Layer 1 Output After Activation::")
print(activation1.output) # output from the activation function

input_batch_layer2 = activation1.output
neurons_layer2 = 3
dense_layer2 = Layer_Dense(len(input_batch_layer2[0]),neurons_layer2)

dense_layer2.forward(input_batch_layer2)

print("Dense Layer 2 output:: ")
print(dense_layer2.output) #For every input batch what is the value from each neuron(3 neurons (columns))

smax_activation = Activation_Softmax()
smax_activation.activate(dense_layer2.output) #Passing through softmax activation at the output layer

print("Dense Layer 2 Output After Softmax Activation::")
print(smax_activation.output) # output from the activation function


Weights are =  [[-0.01306527  0.01658131 -0.00118164]
 [-0.00680178  0.00666383 -0.0046072 ]]
Biases are =  [[0. 0. 0.]]
Dense Layer 1 output:: 
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
Dense Layer 1 Output After Activation::
[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]
Weights are =  [[-0.01334258 -0.01346717  0.00693773]
 [-0.00159573 -0.00133702  0.01077744]
 [-0.01126826 -0.00730678 -0.0038488 ]]
Biases are =  [[0. 0. 0.]]
Dense Layer 2 output:: 
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.8183968e-07 -1.5235776e-07  1.2281279e-06]
 [-5.0631292e-07 -4.2422371e-07  3.4195891e-06]
 [-8.4041352e-07 -7.0415609e-07  5.6760728e-06]
 [-1.1393766e-06 