In [ ]:
# 2-Hidden layer neural network

In [3]:
import numpy as np

#consider each row of input as a feature that is represented by numbers
input_batch1 = [
            [1.0, 2.0, 3.0, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]
         ] # 3 x 4 matrix batch of inputs for a 3 neurons

#weights for layer 1
weights1 = [
            [0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]
          ] # 3 x 4 matrix batch of weights for a 3 neuron

#biases for layer 1
biases1 = [2.0, 3.0 ,0.5]


print("Input Batch = ",input_batch)
print("Weights for Layer1 = ",weights1)
print("Biases for Layer1 = ",biases1)

Input Batch =  [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
Weights for Layer1 =  [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
Biases for Layer1 =  [2.0, 3.0, 0.5]


In [4]:
#Output from layer 1
layer1_outputs = np.dot(input_batch1, np.array(weights1).T) + biases1
print(layer1_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [5]:
#output from layer1 = input to layer2
input_batch2 = layer1_outputs

weights2 = [
            [0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]
           ]
biases2 = [-1, 2, -0.5]

layer2_outputs = np.dot(input_batch2, np.array(weights2).T) + biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
